fns:
  create_new_note:
    args:
    - http_text: null
    event:
    - http_fn: null
  get_notes_mata:
    args:
    - http_text: null
    event:
    - http_fn: null
  rename_note:
    args:
    - http_text: null
    event:
    - http_fn: null
