- name: Check if the file exists
  ansible.builtin.stat:
    path: ../install/inner/WasmEdge-0.13.3-manylinux2014_x86_64.tar.gz
  register: file_stat

- name: Download WasmEdge release file
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/WasmEdge/WasmEdge/releases/download/0.13.3/WasmEdge-0.13.3-manylinux2014_x86_64.tar.gz"
    dest: "../install/inner/WasmEdge-0.13.3-manylinux2014_x86_64.tar.gz"
  when: not file_stat.stat.exists

- name: Install WasmEdge
  become: true
  shell: |
    cat > /tmp/install_wasmedge.sh <<'END'
      #!/bin/bash

      mkdir /tmp/install
      cp scripts/install/inner/WasmEdge-0.13.3-manylinux2014_x86_64.tar.gz /tmp/install/WasmEdge-0.13.3-manylinux2014_x86_64.tar.gz
      python3 scripts/install/inner/wasm_edge.py -v 0.13.3
    END

    bash /tmp/install_wasmedge.sh
    rm -f /tmp/install_wasmedge.sh
  args:
    chdir: "../.."
    creates: "/usr/local/bin/wasmedge" # Skip if WasmEdge is already installed

- name: Debug WasmEdge version
  become: true
  shell: |
    cat > /tmp/debug_wasmedge.sh <<'END'
      #!/bin/bash
      ls /root/.wasmedge/bin/
      export PATH="/root/.wasmedge/bin/":$PATH
      # source ~/.bashrc
      whereis wasmedge
      wasmedge --version
    END

    bash /tmp/debug_wasmedge.sh
    rm -f /tmp/debug_wasmedge.sh
  


