fns:
  add_path:
    args:
    - http_text: null
    event:
    - http_fn: null
  article_binder:
    args:
    - http_text: null
    event:
    - http_fn: null
  article_list:
    args:
    - http_text: null
    event:
    - http_fn: null
  create_new_bar:
    args:
    - http_text: null
    event:
    - http_fn: null
  delete_bar:
    args:
    - http_text: null
    event:
    - http_fn: null
  fetch_all_note_bars_epoch:
    args:
    - http_text: null
    event:
    - http_fn: null
  get_chunk_note_ids:
    args:
    - http_text: null
    event:
    - http_fn: null
  get_note_bar_info:
    args:
    - http_text: null
    event:
    - http_fn: null
  get_note_mata:
    args:
    - http_text: null
    event:
    - http_fn: null
  get_path_info:
    args:
    - http_text: null
    event:
    - http_fn: null
  redo:
    args:
    - http_text: null
    event:
    - http_fn: null
  remove_path:
    args:
    - http_text: null
    event:
    - http_fn: null
  set_path_info:
    args:
    - http_text: null
    event:
    - http_fn: null
  update_bar_content:
    args:
    - http_text: null
    event:
    - http_fn: null
  update_bar_transform:
    args:
    - http_text: null
    event:
    - http_fn: null
